node:
  wan-rtr:
    routing:
      lo: 10.5.5.5/32
      bgp:
        asn: 65555
        underlay:
          external:
            peers:
              - swp1
              - swp2
          internal:
            peers:
  agg-switch01:
    routing:
      lo: 10.4.4.1/32
      bgp:
        asn: 65444
        underlay:
          external:
            peers:
              - swp1
              - swp2
              - swp3
              - swp20
          internal:
            peers:
              - swp10
              - swp11
  agg-switch02:
    routing:
      lo: 10.4.4.2/32
      bgp:
        asn: 65444
        underlay:
          external:
            peers:
              - swp1
              - swp2
              - swp3
              - swp20
          internal:
            peers:
              - swp10
              - swp11
