node:
  closet-switch01:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp11
      - swp12
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  closet-switch02:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp21
      - swp22
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  closet-switch03:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp31
      - swp32
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo:
      ospf:
        area:
        neighbors:
      bgp:
        asn:
        underlay:
          external:
            peers:
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
