node:
  closet-switch01:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 100
    routing:
      lo: 10.1.1.1/32
      bgp:
        asn: 65111
        underlay:
          external:
            peers:
              - swp1
              - swp2
      svi:
        vlan100:
          ip: 10.11.11.1/24
          vlan: 100
  closet-switch02:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 100
    routing:
      lo: 10.2.2.2/32
      bgp:
        asn: 65222
        underlay:
          external:
            peers:
              - swp1
              - swp2
      svi:
        vlan100:
          ip: 10.22.22.1/24
          vlan: 100
  closet-switch03:
    switching:
      interface:
        swp7:
          mode: access
          vlan: 100
      vlans:
        - 100
    routing:
      lo: 10.3.3.3/32
      bgp:
        asn: 65333
        underlay:
          external:
            peers:
              - swp1
              - swp2
      svi:
        vlan100:
          ip: 10.33.33.1/24
          vlan: 100
