---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Initial Hostname setup
  nclu:
    commit: true
    description: "Initial Hostname setup"
    commands:
      - add hostname "{{ inventory_hostname }}"

- name: Deploy VLAN and SVI configurations
  nclu:
    commit: true
    description: "Deploy VLAN and SVI configurations"
    template: |
      add vlan {{ item.value.vlan }} ip address {{ item.value.ip }}
  with_dict:
    - "{{ node[inventory_hostname].routing.svi }}"

- name: Deploy VLAN and SVI configurations
  nclu:
    commit: true
    description: "Deploy VLAN and SVI configurations"
    template: |
      add vlan {{ item.value.vlan }} ip address {{ item.value.ip }}
      net add bridge bridge ports {{ item.value.ports }}
  with_dict:
    - "{{ node[inventory_hostname].routing.svi }}"
